### PR TITLE
Milestone-1: Project setup

### PR DESCRIPTION
**Pull request by kubilaycaglayan**
Dear TSE,

In this step we created two folders:

1. bin
- main.rb
2. lib
- .gitkeep

**You are able to run "main.rb" solely on your command line and run the hello world code.**

Stickler files are also added.

With all our respects...

### CODE REVIEW

**Comment by majovanilla** [comment]
Hey team!! 

Great work!! Your milestone has all the technical requirements! :star: 
Your pull request message is perfect!!

Just a little thing before moving on:

Improve your Readme file. It should be descriptive of the project. You are using the correct template but now you need to fill it with information about your project. You can add details about what you did in this project, why you did it, how you did it...Check this [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) for more info.

Also, you are not using some sections of the readme, which is ok... just delete them.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

**Comment by kubilaycaglayan** [comment]
Dear TSE,

[README](https://github.com/ikraamg/TIC-TAC-TOE/blob/initializing_files/README.md) file edited.

With all of our respects...

**Comment by ikraamg** [comment]
Good day, we have made the changes as requested. Please note that only the final milestone requires the readme to be completed correctly. We did not correct our readme in our first requested review due to that information.

**Review by whiz25 — APPROVED** [review]
## Approved :clap:
You have satisfied the minimum requirements for this milestone. Please move forward to the next.

### Martin Afani

**Pull request merged**
